export const siteConfig = {
  name: 'Pratyush Sharma Portfolio',
  title: 'Pratyush Sharma - Software Engineer',
  description: 'Software Engineer with 2+ years of experience building scalable microservices and cloud-based applications using Python, Java, FastAPI, and Spring Boot.',
  url: 'https://pratyush-portfolio.vercel.app',
  ogImage: 'https://pratyush-portfolio.vercel.app/og-image.png',
  author: {
    name: 'Pratyush Sharma',
    role: 'Software Engineer',
    bio: 'Software Engineer with 2+ years of experience building scalable microservices and cloud-based applications using Python, Java, FastAPI, and Spring Boot. Built marketing automation flows using AI agents that improved user engagement by 71%. Skilled in RESTful API design, Dockerized deployments, AWS services, and system design following SOLID principles.',
    location: 'Noida, Uttar Pradesh',
    email: 'ps8404233@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
  },
  social: {
    github: 'https://github.com/pratyush618',
    linkedin: 'https://linkedin.com/in/pratyush1909',
    email: 'ps8404233@gmail.com',
  },
  experience: [
    {
      id: '1',
      company: 'Compliance Innovation',
      role: 'Software Engineer',
      period: 'Nov 2024 - Present',
      location: 'India',
      description: 'Engineering microservice architectures and AI-powered automation solutions for marketing workflows and blockchain compliance.',
      achievements: [
        'Engineered a complete microservice architecture to automate marketing workflows using AI agents, boosting user engagement by 71.3%',
        'Designed and implemented ETL pipelines with Python and FastAPI to ingest, transform, and store large volumes of data',
        'Integrated Scorechain technology to monitor and score blockchain wallets and transactions, enhancing risk assessment capabilities and increasing suspicious activity detection by 45%',
        'Upgraded an existing WebRTC project with Agora, reducing latency by 40% and improving video feed quality'
      ],
      technologies: ['Python', 'FastAPI', 'Scorechain', 'WebRTC', 'Agora', 'AI Agents', 'ETL Pipelines'],
    },
    {
      id: '2', 
      company: 'Netprophets Cyberworks Pvt. Ltd.',
      role: 'Software Engineer Trainee',
      period: 'Jan 2024 - Oct 2024',
      location: 'India',
      description: 'Integrated AWS services for email management, re-architected systems for multi-tenancy, and ensured PCI DSS compliance.',
      achievements: [
        'Integrated AWS services (SNS, SQS, and SES) for comprehensive email monitoring and management, improving bounce tracking accuracy by 25% and reducing email delivery failures by 18%',
        'Re-architected existing systems to support multi-tenant configurations, enabling a 30% increase in scalability and streamlining payment gateway integrations, reducing transaction failures by 15%',
        'Optimized and streamlined code workflows, increased invoice and credit note processing efficiency by 20%, and reduced financial report errors by 25%',
        'Assisted in the 2024 PCI DSS audit, ensuring 100% compliance with industry security standards and mitigating potential penalties of up to $50,000'
      ],
      technologies: ['AWS SNS', 'AWS SQS', 'AWS SES', 'Multi-tenant Architecture', 'Payment Gateways', 'PCI DSS'],
    },
  ],
  education: [
    {
      id: '1',
      institution: 'Rajkiya Engineering College',
      degree: 'B.Tech',
      field: 'Computer Science & Engineering',
      period: '2019 - 2023',
      description: 'Comprehensive education in computer science fundamentals, programming, and software engineering.',
      achievements: [
        'Strong foundation in data structures and algorithms',
        'Gained expertise in multiple programming languages and frameworks',
        'Member of College\'s Web Design and Media Council (WDMC)',
        'Developed teamwork and communication skills through various projects'
      ],
    },
  ],
  projects: [
    {
      id: '1',
      title: 'AI-Powered Marketing Automation Platform',
      description: 'Complete microservice architecture using AI agents for marketing workflow automation, achieving 71.3% improvement in user engagement.',
      longDescription: 'Engineered a comprehensive microservice architecture that leverages AI agents to automate complex marketing workflows. The system includes ETL pipelines built with Python and FastAPI for data processing, analytics features, and real-time reporting capabilities.',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
      technologies: ['Python', 'FastAPI', 'AI Agents', 'Microservices', 'ETL Pipelines', 'Analytics'],
      liveUrl: '',
      githubUrl: '',
      featured: true,
      category: 'AI/ML',
    },
    {
      id: '2',
      title: 'Blockchain Risk Assessment System',
      description: 'Integration of Scorechain technology for monitoring and scoring blockchain wallets and transactions, enhancing compliance capabilities.',
      longDescription: 'Developed a comprehensive blockchain monitoring system that integrates Scorechain technology to analyze and score cryptocurrency transactions and wallets. The system increased suspicious activity detection by 45% and ensures robust compliance with financial regulations.',
      image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=600&fit=crop',
      technologies: ['Scorechain', 'Blockchain Analysis', 'Risk Assessment', 'Compliance', 'Financial Regulations'],
      liveUrl: '',
      githubUrl: '',
      featured: true,
      category: 'Blockchain',
    },
    {
      id: '3',
      title: 'Multi-Tenant AWS Integration Platform',
      description: 'Re-architected systems for multi-tenant configurations with comprehensive AWS services integration for email management and payment processing.',
      longDescription: 'Designed and implemented a scalable multi-tenant architecture that integrates AWS SNS, SQS, and SES for comprehensive email monitoring. The system improved bounce tracking accuracy by 25%, reduced email delivery failures by 18%, and streamlined payment gateway integrations.',
      image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop',
      technologies: ['AWS SNS', 'AWS SQS', 'AWS SES', 'Multi-tenancy', 'Payment Gateways', 'Email Management'],
      liveUrl: '',
      githubUrl: '',
      featured: true,
      category: 'Cloud Infrastructure',
    },
  ],
  skills: {
    'Programming Languages': [
      'Java',
      'Python',
      'TypeScript',
      'JavaScript',
    ],
    'Frameworks & Libraries': [
      'FastAPI',
      'Spring Boot',
      'Node.js',
      'Agora',
      'Langchain',
    ],
    'Databases': [
      'MySQL',
      'PostgreSQL',
      'MongoDB',
    ],
    'Cloud & DevOps': [
      'AWS SNS',
      'AWS SQS', 
      'AWS SES',
      'AWS S3',
      'Docker',
      'Postman',
    ],
    'Build Tools & Version Control': [
      'Maven',
      'Gradle',
      'Git',
      'GitLab',
    ],
    'Design Principles & Architecture': [
      'SOLID Principles',
      'REST APIs',
      'SOA (Service-Oriented Architecture)',
      'Microservices',
      'Multi-tenant Architecture',
    ],
  },
  navigation: [
    { name: 'About', href: '#about' },
    { name: 'Experience', href: '#experience' },
    { name: 'Education', href: '#education' },
    { name: 'Projects', href: '#projects' },
    { name: 'Skills', href: '#skills' },
    { name: 'Blog', href: '#blog' },
    { name: 'Contact', href: '#contact' },
  ],
}
